### ISSUE TITLE
Is it supported in terminal emacs now?

### ISSUE THREAD

**Issue by LimingFang** [manateelazycat/blink-search#16]
When typing `blink-search`, it shows:
![](https://emacs-china.org/uploads/default/original/3X/e/0/e0f4f870bc67484231bdcd0c907d1d2c009b577b.png)

I tried:

![](https://emacs-china.org/uploads/default/original/3X/0/9/0994303d3c3e504d1a20a9a2b1f368bf481ece70.png)

But it doesn't work

**Comment by manateelazycat** [comment]
要解决你这个问题很简单， 随便在 blink-search 之前加载一个主题即可。
