### ISSUE TITLE
`!` not work well in Debian terminal

### ISSUE THREAD

**Issue by LimingFang** [manateelazycat/blink-search#23]
# How to reproduce:
- debian OS and `fd`, `ripgrep` and other dependency have all been installed:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/28479651/201820643-05daa6db-35b5-4655-920b-21c5ed5eb740.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/28479651/201820709-c6ca8447-f3dd-4928-8e2d-632ca408172b.png">

-  `emacs -Q` and only load `blink-search` package.  

# what the problem is：
## 1
open random git repo, `M-x blink-search`. First I test **prefix #** to find in current buffer, it's ok:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/28479651/201821285-86783e1d-06e7-42fb-89d3-8c4a9852df76.png">

## 2
Then I tried `!`:
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/28479651/201821494-6ec765c7-5122-4d64-bd11-6f26377b6a2b.png">
Nothing appears.

# what I did:
## 1
I open `*blink-search*`:
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/28479651/201821781-a5cccd78-76c0-4e67-be3c-18f4be5839c2.png">

It seems that the `fd` should be used as `fdfind` on debian, so I made some change:
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/28479651/201822090-07f39cc8-5964-4c43-b101-afdaea785c6c.png">

## 2
But new issue arose:
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/28479651/201822150-ed44cf92-883f-4360-95c2-764c703d6101.png">
I guess there's something wrong with my *VPN*, so I chose to close the backend:
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/28479651/201822295-40272067-419b-45a1-8662-22c2420188bb.png">

## 3
But other problem arose: 
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/28479651/201822472-414488d4-af1e-4251-9d8c-c5034038c471.png">

**Comment by manateelazycat** [comment]
你更新到最新版测试一下看看修好了没， 应该会自动支持 fdfind ， 不用修改源代码。

**Comment by manateelazycat** [comment]
Please commit new issue if you still have problem, thanks for reported ! ;)
