### ISSUE TITLE
`!` not work well 

### ISSUE THREAD

**Issue by LimingFang** [manateelazycat/blink-search#24]
See #23 ，after applying the newest patch, i still have some questions.
`#` is ok, but when i use `!`, the `*blink-search*` didn't output anything:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/28479651/202072520-965a65cd-5410-4af0-a09f-e96c47009665.png">

**Comment by LimingFang** [comment]
我需要提供其他细节吗

**Comment by manateelazycat** [comment]
你用 rg 命令， 在终端中同样的目录下搜索同样关键字， 看看有没有输出， 你的问题比较诡异。

目前看 blink-search 只是没有报错， 但是不知道为什么 rg 子进程没有输出。

**Comment by LimingFang** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/28479651/202109698-ece37772-a14f-486c-960d-110eb9e238d8.png">
这个吗，哦不对，等一下哈

**Comment by LimingFang** [comment]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/28479651/202111367-ae6642ba-2ddc-47d6-9235-e7ce2ec9149e.png">
<img width="902" alt="image" src="https://user-images.githubusercontent.com/28479651/202111552-568629db-253a-43f7-87c0-974a5c24645e.png">

**Comment by LimingFang** [comment]
我知道为啥了，我提个 PR 吧

**Comment by LimingFang** [comment]
我把 commandlist 里 no-binary 删除了，因为 rg 默认无视 binary-file，然后给 -g 后加了单引号，这样命令行下是 ok 的，但是 emacs 中还是没有：
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/28479651/202119239-39be4892-8441-4965-b9a4-aa151a408e6f.png">

**Comment by manateelazycat** [comment]
确实有开发者告诉过我， 如果目录下有些特殊的二进制会导致 rg 没法搜索结果。

但是我现在不知道为什么， 你能给 rg 加上 debug 类似的选项看看 rg 有没有啥线索吐出来？

**Comment by LimingFang** [comment]
ok 我试试

**Comment by LimingFang** [comment]
command list 中删除  "--no-binary" 就 ok 了。然后我去看了下 rg， 它好像默认就无视 binary 的吧，以及没有  "--no-binary" option 诶。anyway 我删了就 work 了。
