### ISSUE TITLE
how to make it work with embark

### ISSUE THREAD

**Issue by emacsbliss** [manateelazycat/blink-search#28]
for eg, after I did a search, is it possible to use something like embark to save the result into a separate buffer?

**Comment by manateelazycat** [comment]
Why need save result into a separate buffer? 

What's purpose for save result?

**Comment by emacsbliss** [comment]
Sometimes I want to save the search result into a separate buffer so I can go through each result and do something about it.

By having a buffer so I don't have to re-run the search again and again (even if the search is very fast).

Maybe blink-search already supports something like that, in that case would like to know how to use it.

Thanks!

**Comment by manateelazycat** [comment]
i can't understand what you say

**Comment by suliveevil** [comment]
> Sometimes I want to save the search result into a separate buffer so I can go through each result and do something about it.

What's the point of dealing with ** intermediate data** during the search for **target data**?

You can use grep with pipe xargs redirection ... in shell to get what you want.

And you can save your search commands to register file or elsewhere, then evaluate it again and again.

Or bind commands to temporary key bindings:

https://github.com/0x60df/loophole

The only limitation is your imagination.

**Comment by ksqsf** [comment]
I sympathize with this proposal. `embark-export` is an important feature. (`embark-export` is similar to `ivy-occur` but framework-agnostic.) But I confess I don't have a good idea for implementing this for a multiple-source search engine like blink-search.

-----

I will try to sell this feature then.

I use this feature frequently, and consider it a great advantage of the Emacs ecosystem. It streamlines the following use cases:

1. It provides a unified entry to occur[-edit-mode] (e.g. `consult-lines`), [w]grep (e.g. `consult-git-grep`), etc.
2. When you want to pick multiple choices. For example, the Google backend can suggest multiple choices for a single search term. What if you want to see the results for all of them? By default, you would have to repeat the same search again and again, but with `embark-export` you can try all of them easily.
3. Save the search results for further processing. It opens a new buffer, which can be saved to files by typing C-x C-s.

Shell scripting is not a replacement nor an alternative. The "exported" buffer can be interacted with, and can freely use data inside Emacs. (Think `occur`.)

-----

More on Use Case 2. Of course, it is not limited to Google. I usually use it with `xref-find-references`. For example, when doing a refactor, I need to check which of the reference should be updated.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/23358293/204237258-cf569ae3-2778-448b-9931-410fa0e4aa95.png">

It's a pain in the ass to (1) press `M-?`; (2) choose n-th reference and check the code there; (3) back to (1) until the process finished. However, with embark-export:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/23358293/204237664-5a6731eb-8dad-48e3-83b6-63d1f90ee315.png">

I can now just press Enter on the corresponding line to see the code, and the buffer won't disappear like the minibuffer.

**Comment by manateelazycat** [comment]
> I sympathize with this proposal. `embark-export` is an important feature. (`embark-export` is similar to `ivy-occur` but framework-agnostic.) But I confess I don't have a good idea for implementing this for a multiple-source search engine like blink-search.
> 
> I will try to sell this feature then.
> 
> I use this feature frequently, and consider it a great advantage of the Emacs ecosystem. It streamlines the following use cases:
> 
> 1. It provides a unified entry to occur[-edit-mode] (e.g. `consult-lines`), [w]grep (e.g. `consult-git-grep`), etc.
> 2. When you want to pick multiple choices. For example, the Google backend can suggest multiple choices for a single search term. What if you want to see the results for all of them? By default, you would have to repeat the same search again and again, but with `embark-export` you can try all of them easily.
> 3. Save the search results for further processing. It opens a new buffer, which can be saved to files by typing C-x C-s.
> 
> Shell scripting is not a replacement nor an alternative. The "exported" buffer can be interacted with, and can freely use data inside Emacs. (Think `occur`.)
> 
> More on Use Case 2. Of course, it is not limited to Google. I usually use it with `xref-find-references`. For example, when doing a refactor, I need to check which of the reference should be updated.
> 
> <img alt="image" width="514" src="https://user-images.githubusercontent.com/23358293/204237258-cf569ae3-2778-448b-9931-410fa0e4aa95.png">
> 
> It's a pain in the ass to (1) press `M-?`; (2) choose n-th reference and check the code there; (3) back to (1) until the process finished. However, with embark-export:
> 
> <img alt="image" width="612" src="https://user-images.githubusercontent.com/23358293/204237664-5a6731eb-8dad-48e3-83b6-63d1f90ee315.png">
> 
> I can now just press Enter on the corresponding line to see the code, and the buffer won't disappear like the minibuffer.

why not use color-rg.el ?

**Comment by ksqsf** [comment]
> why not use color-rg.el ?

color-rg only covers a fraction of the prospective use cases. For example, it does not deal with in-buffer searches (`occur`), nor it does not work with LSP, etc. I consider "unified entry" the primary benefit of such a feature.

**edit**: and ofc I don't mean blink-search _must_ integrate with embark. blink-search could offer its own version to overcome some possible limitations of embark.

**Comment by manateelazycat** [comment]
> > why not use color-rg.el ?
> 
> color-rg only covers a fraction of the prospective use cases. For example, it does not deal with in-buffer searches (`occur`), nor it does not work with LSP, etc. I consider "unified entry" the primary benefit of such a feature.
> 
> **edit**: and ofc I don't mean blink-search _must_ integrate with embark. blink-search could offer its own version to overcome some possible limitations of embark.

no, color-rg.el can search current buffer content

**Comment by ksqsf** [comment]
> no, color-rg.el can search current buffer content

Thanks for the correction.

**Comment by manateelazycat** [comment]
> Sometimes I want to save the search result into a separate buffer so I can go through each result and do something about it.
> 
> By having a buffer so I don't have to re-run the search again and again (even if the search is very fast).
> 
> Maybe blink-search already supports something like that, in that case would like to know how to use it.
> 
> Thanks!

Please use color-rg.el.
