### ISSUE TITLE
请问猫大可以考虑下支持中文全角字符的搜索前缀吗？

### ISSUE THREAD

**Issue by suliveevil** [manateelazycat/blink-search#29]
有时想搜索中文，grep buffer 用的前缀 `#` 在中英文下是一样的，但前缀 `!` 和 `;` 中英文下不一样，就需要有一次输入法切换。

https://github.com/manateelazycat/blink-search/blob/def0cdaf800a897083e1930eaff7c601cae2b712/blink-search.el#L593

或者通过让 blink-search 支持 repeat-mode，按一次绑定的快捷键切换一次后端，这样就能去掉前缀和专门用来切换后端的快捷键了，而且手指不用改变位置。

这个想法来自 isearch-forward 和这个函数：

```emacs-lisp
;; goto-char by Oliver Scholz
(defun wy-go-to-char (n char)
  "Move forward to Nth occurence of CHAR.
Typing `wy-go-to-char-key' again will move forwad to the next Nth
occurence of CHAR."
  (interactive "p\ncGo to char: ")
  (search-forward (string char) nil nil n)
  (while (char-equal (read-char)
                     char)
    (search-forward (string char) nil nil n))
  (setq unread-command-events (list last-input-event)))

(define-key global-map (kbd "C-c a") 'wy-go-to-char)
```

函数的出处：

https://docs.huihoo.com/homepage/shredderyin/emacs_elisp.html

**Comment by manateelazycat** [comment]
中文前缀已经加了。

但是我不想搞按键切换这种， blink-search 本来就是带两种模式： 正常搜索和探索性搜索 (rg, rga), 这两个场景一般都是开始就会确定怎么搜索， 不会中途切换的。

我不想把插件搞的那么复杂， 抱歉。

**Comment by suliveevil** [comment]
😂 我只是天马行空一下，blink-search 这么强大还是不搞花里胡哨的为好。
