### ISSUE TITLE
首次运行 blink-search ，*blink-search* 提示：ERROR:epc:ReturnError([Symbol('void-function'), Symbol('acm-backend-elisp-local-symbols')])

### ISSUE THREAD

**Issue by czqhurricnae** [manateelazycat/blink-search#34]
# 现象
如题，所有的 blink-search window 空白。C-g，后再次调用才能出现内容。
*blink-search* 提示：ERROR:epc:ReturnError([Symbol('void-function'), Symbol('acm-backend-elisp-local-symbols')])
# 1
提示指向：
https://github.com/manateelazycat/blink-search/blob/d5c415fbd766f79e51d0325b1ddc55aa703a6550/backend/blink-search-elisp-symbol.el#L102-L110

# 2
```
(setq blink-search-search-backends '("Grep PDF" "Buffer List" "Find File" "Common Directory" "Recent File" "Grep File" "IMenu" "EAF Browser History"))
```

也就是将 Elisp Symbol 从 backends 删除。重启，还是一样的现象。

按照理解，blink-search-elisp-symbol.el 不会被执行吧。但是：
https://github.com/manateelazycat/blink-search/blob/d5c415fbd766f79e51d0325b1ddc55aa703a6550/backend/blink-search-elisp-symbol.el#L102-L110
函数还是执行了。

该函数是被 blink-search-start-elisp-symbol-update 调用

blink-search-elisp-symbol.el 文件中：
```
(add-to-list 'blink-search-idle-update-list #'blink-search-start-elisp-symbol-update t)

```
在 blink-search.el 中：
```
(defun blink-search--first-start (blink-search-epc-port)
  "Call `blink-search--open-internal' upon receiving `start_finish' signal from server."
  ;; Make EPC process.
  (setq blink-search-epc-process (make-blink-search-epc-manager
                                  :server-process blink-search-internal-process
                                  :commands (cons blink-search-internal-process-prog blink-search-internal-process-args)
                                  :title (mapconcat 'identity (cons blink-search-internal-process-prog blink-search-internal-process-args) " ")
                                  :port blink-search-epc-port
                                  :connection (blink-search-epc-connect "localhost" blink-search-epc-port)
                                  ))
  (blink-search-epc-init-epc-layer blink-search-epc-process)
  (setq blink-search-is-starting nil)

  (dolist (update-func blink-search-idle-update-list)
    (funcall update-func))

  (dolist (update-func blink-search-start-update-list)
    (funcall update-func)))
```

也就是不管 backend 是否有 Elisp Symbol，都会执行 
https://github.com/manateelazycat/blink-search/blob/d5c415fbd766f79e51d0325b1ddc55aa703a6550/backend/blink-search-elisp-symbol.el#L102-L110

。

所以导致错误提示。

**Comment by manateelazycat** [comment]
已经修复了， 这些代码是从 lsp-bridge 拷贝过来的， 名字没有重命名彻底。
