### ISSUE TITLE
Preview doesn't work well after native-comp

### ISSUE THREAD

**Issue by mumu-lhl** [manateelazycat/blink-search#36]
I use blink-search after native-comp. I found out that its preview is not working properly:

![image](https://user-images.githubusercontent.com/75873372/222945648-bf649efe-ec6b-467a-b039-6a6a8973a5ca.png)

Important log:

```
Eval in Emacs: (blink-search-current-buffer-preview '"blink-search-current-buffer.el" '3 '13)
ERROR:epc:ReturnError([Symbol('invalid-function'), Symbol('blink-search-select-input-window')])
```

**Comment by manateelazycat** [comment]
Please don't use native comp, it not design for it.

**Comment by vinurs** [comment]
@manateelazycat 好像编译成 elc 文件以后执行这个命令也会报上面的错误，我删除了 elc 文件以后就好了，是否在这个几个文件里面加上 ` no-byte-compile: t;`

**Comment by manateelazycat** [comment]
@vinurs 大佬发补丁吧， 我平常不用 native-comp. ;)

**Comment by vinurs** [comment]
@manateelazycat 我提了一个 PR，您看一下哈 https://github.com/manateelazycat/blink-search/pull/49
