### ISSUE TITLE
Group grep results by files

### ISSUE THREAD

**Issue by fountainer** [manateelazycat/blink-search#39]
目前grep 和rga 的搜索结果的呈现方式是扁平的，也就是每一行匹配结果同时包含文件名和匹配的文本，不过当文件名较长时（包括路径层次比较深），一行容易显示不全。希望可以分组显示搜索结果，分组标题即为文件名（包含路径），分组下面只显示匹配的文本。另外，希望提供 next group 这样的命令来跳转分组。

**Comment by manateelazycat** [comment]
这种交互模式， 我估计 color-rg 会更加适合。

blink-search 的目标是融合多个搜索后端替换 helm 的， 如果某一个后端再做文件分组，就会导致代码过于复杂， 没法维护。
