### ISSUE TITLE
强制kill emacs 进程后，python服务器进程没有退出机制

### ISSUE THREAD

**Issue by heheda123123** [manateelazycat/blink-search#44]
如图，今天使用blink-search，用!搜索目录的时候存在卡死的情况，卡死后我用进程管理器把emacs进程杀了，但是 blink-search.py包括这几个rg进程都还在运行，是不是得有个机制保证对端的emacs关闭后自动退出这边python服务器进程

![image](https://github.com/manateelazycat/blink-search/assets/97490782/3de02811-e5c9-4ce3-a929-a6a19231737d)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lazycat-emacs/blob/43f7de77cfe31034982e61c477c0eeb30c697427/site-lisp/config/init-generic.el#L114

**Comment by heheda123123** [comment]
看来得养成看源码的习惯，之前只是看了readme

**Comment by heheda123123** [comment]
貌似没有解决问题。这个设置应该是emacs正常退出时才会kill子进程。但是如果emacs异常卡死。手动把emacs进程kill了，他的子进程并不会自动被kill。
我的意思是可以考虑在python-bridge.py这边做心跳机制之类的，如果对端的emacs无了就自动关闭。
不过问题也不大，卡死的情况不多。

**Comment by manateelazycat** [comment]
强制杀的， 自己杀吧， Emacs怎么卡死就给对应的项目报bug吧。

心跳就不要做了， 为了小众情况把事情搞复杂了。
