### ISSUE TITLE
blink-search-parent打开候选文件所在目录失败

### ISSUE THREAD

**Issue by kapmix** [manateelazycat/blink-search#53]
搜索一个文件名，特别是二进制的文件名，如.azw3，blink-search会显示相对于当前文件夹的路径名。想用C-j blink-search-parent函数打开该文件所在的目录，却失败了，打开的是该二进制文件。
![image](https://github.com/user-attachments/assets/b5134e1d-a748-41d9-87aa-2d67662aaa41)
![image](https://github.com/user-attachments/assets/022fbc29-bdf3-4b26-9a58-57ce1ce814e7)

**Comment by kapmix** [comment]
跟踪了一下，C-j调用了search_find_file.py

**Comment by manateelazycat** [comment]
Fix by https://github.com/manateelazycat/blink-search/commit/e018c5cc435a0278770cd864147efa65fbcf84d5
