### ISSUE TITLE
使用doom-one主题报错

### ISSUE THREAD

**Issue by Jack126** [manateelazycat/blink-search#54]
如题，使用 doom-theme ，doom-one主题 报错。默认init.el 配置，仅引入blink-search

**Comment by manateelazycat** [comment]
报什么错？

**Comment by Jack126** [comment]
ebugger entered--Lisp error: (wrong-number-of-arguments (((alpha . 0.6) (c2 . "#000000") (c1 . "unspecified-bg") t) (r g b) (format "#%02x%02x%02x" (ash r -8) (ash g -8) (ash b -8))) 0)
  (closure ((alpha . 0.6) (c2 . "#000000") (c1 . "unspecified-bg") t) (r g b) (format "#%02x%02x%02x" (ash r -8) (ash g -8) (ash b -8)))()
  apply((closure ((alpha . 0.6) (c2 . "#000000") (c1 . "unspecified-bg") t) (r g b) (format "#%02x%02x%02x" (ash r -8) (ash g -8) (ash b -8))) nil)
  blink-search-color-blend("unspecified-bg" "#000000" 0.6)
  (set-face-background 'blink-search-select-face (blink-search-color-blend default-background blend-background 0.6))
  (progn (set-face-background 'blink-search-select-face (blink-search-color-blend default-background blend-background 0.6)))
  (if (or force (equal (face-attribute 'blink-search-select-face :background) 'unspecified)) (progn (set-face-background 'blink-search-select-face (blink-search-color-blend default-background blend-background 0.6$
  (let* ((is-dark-mode (string-equal (blink-search-get-theme-mode) "dark")) (blend-background (if is-dark-mode "#000000" "#AAAAAA")) (default-background (face-attribute 'default :background))) (if (or force (equa$
  blink-search-init-colors()
  blink-search(nil)
  funcall-interactively(blink-search nil)
  call-interactively(blink-search record nil)
  command-execute(blink-search record)
  execute-extended-command(nil "blink-search" "blink-se")
  funcall-interactively(execute-extended-command nil "blink-search" "blink-se")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by manateelazycat** [comment]
更新最新版吧， 已经修好了

**Comment by Jack126** [comment]
搞定，感谢🙏🙏🙏
